# Generated by Django 5.1 on 2024-08-25 07:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.get_code, max_length=8, unique=True),
        ),
    ]
