# Generated by Django 5.1 on 2024-08-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_song',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
